export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';

export const INCREMENT_REQUESTS_COUNT = 'INCREMENT_REQUESTS_COUNT';
export const DECREMENT_REQUESTS_COUNT = 'DECREMENT_REQUESTS_COUNT';

export const DEPOSIT = 'DEPOSIT';
export const WITHDRAW = 'WITHDRAW';
